spring.application.name=freightflow360-backend

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/freightflow360_db
spring.datasource.username=root
spring.datasource.password=Jelly123fi$h

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origin=http://localhost:4200

app.jwt.secret=YWRtaW5BdXRoU2VjcmV0S2V5Rm9yV2FyZWhvdXNlUHJvamVjdDIwMjY=
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=http://localhost:4200